
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: invoice-app
  replicas: 3
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: invoice-app
        image: dockersara1234/it19141848
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: invoice-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer