apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-05-16T18:13:21Z"
  generation: 1
  labels:
    app: it19141848

    manager: kubectl
    operation: Update
    time: "2022-05-16T18:13:21Z"
  name: it19141848
  namespace: default
  resourceVersion: "944"
  selfLink: /apis/apps/v1/namespaces/default/deployments/it19141848
  uid: 0384ca05-dc00-4881-b5ca-0a0503c9c664
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: it19141848
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: it19141848
    spec:
      containers:
      - image: dockersara1234/it19141848
        imagePullPolicy: Always
        name: it19141848
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8080
      dnsPolicy: ClusterFirst