apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: it19141848
  name: it19141848
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: it19141848
status:
  loadBalancer: {}